logging.level.root=INFO
logging.level.com.vn.son.jobhunter=INFO
logging.level.com.vn.son.jobhunter.service.EmailService=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate=ERROR

