logging.level.root=INFO
logging.level.com.vn.son.jobhunter=INFO
logging.level.org.springframework.security=INFO
logging.level.org.hibernate=ERROR

logging.file.name=${JOBHUNTER_LOG_FILE:logs/jobhunter-staging.log}
management.endpoint.health.show-details=always
management.tracing.enabled=${MANAGEMENT_TRACING_ENABLED:true}
management.tracing.sampling.probability=${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:0.25}

jobhunter.swagger.enabled=${JOBHUNTER_SWAGGER_ENABLED:true}
