logging.level.root=ERROR
logging.level.com.vn.son.jobhunter=WARN
logging.level.org.springframework.test=ERROR
spring.main.banner-mode=off
jobhunter.seed.enabled=false
jobhunter.scheduler.enabled=false
jobhunter.scheduler.mail.enabled=false
jobhunter.scheduler.weekly-recommendation.enabled=false
